apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Jira Bug Aging Report

on:
 # schedule:
    # Run every Monday at 9:00 AM UTC
  #  - cron: '0 9 * * 1'
  # Allow manual trigger
  workflow_dispatch:
  # Optional: Run on push to main
  push:
    branches:
      - main

jobs:
  generate-bug-report:
    steps:
      - name: Checkout code
        uses: cloudbees-io/checkout@v1

      - name: Configure AWS credentials via OIDC
        uses: cloudbees-io/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/infra-claude-bedrock-ci
          aws-region: us-east-1

      - name: Verify AWS credentials
        uses: docker://amazon/aws-cli:2.33.26
        shell: sh
        run: |
          aws sts get-caller-identity
          echo "✅ Successfully authenticated to AWS"

      - name: Set up Python
        uses: docker://python:3.15.0a6
        with:
          python-version: '3.13'

      - name: Install Python dependencies
        uses: docker://python:3.15.0a6
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Jira Bug Summarizer
        uses: docker://python:3.15.0a6
        env:
          JIRA_URL: https://cloudbees.atlassian.net
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          AWS_REGION: us-east-1
          BEDROCK_MODEL_ID: us.anthropic.claude-sonnet-4-5-20250929-v1:0
        run: |
          echo "Starting Jira Bug Summarizer..."
          python jira_bug_summarizer.py
          echo "✅ Bug report generation completed"

      - name: Display report summary
        uses: docker://golang:1.20.3-alpine3.17
        run: |
          echo "📊 Generated Reports:"
          if [ -f bug_report.json ]; then
            echo "✅ bug_report.json ($(wc -l < bug_report.json) lines)"
          fi
          if [ -f bug_report.txt ]; then
            echo "✅ bug_report.txt"
            echo ""
            echo "📄 Report Preview (first 50 lines):"
            head -n 50 bug_report.txt
          fi

      - name: Upload bug reports as artifacts
        uses: cloudbees-io/upload-artifact@v1
        with:
          name: jira-bug-reports-${{ cloudbees.scm_sha_short }}
          path: |
            bug_report.json
            bug_report.txt

      - name: Archive reports with timestamp
        uses: docker://golang:1.20.3-alpine3.17
        run: |
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          mkdir -p reports_archive
          cp bug_report.json reports_archive/bug_report_${TIMESTAMP}.json
          cp bug_report.txt reports_archive/bug_report_${TIMESTAMP}.txt
          echo "✅ Reports archived with timestamp: ${TIMESTAMP}"
